デザインの修正とモーダルウインドウの表示機能の作成を行いました
team-red-2203/workshop-omikuji pull request #11
Opened 2022-03-30 13:23 UTC by satofumiya

崩してしまっていたデザインの修正とid,classの調整を行いました。

2022-03-30 13:43 UTC, hirotada-t requested changes
結果画面の画像パスを修正ください。

2022-03-30 13:43 UTC, hirotada-t commented on index.html
> +              <img src="imgOmikuji/onepiece01_luffy.png" class="col-8">
パスが変わっていますね。

ディレクトリ構造を変えて、
./img/imgOmikuji/onepiece01_luffy.png
にするのが良いかと！

2022-03-30 13:57 UTC, satofumiya commented on index.html
> +              <img src="imgOmikuji/onepiece01_luffy.png" class="col-8">
ファイルの位置の変更とHTMLの修正しました！確認よろしくお願いします

2022-03-30 14:01 UTC, hirotada-t approved these changes
ありがとうございます！

2022-03-31 16:26 UTC, yoshiryo413 approved these changes
daikichi.htmlの画面をindex.htmlの画面にモーダル表示するためにjsファイルを書き換えてるって感じですかね？
今からモーダル表示する様にしていくって感じかな？？addEventListenerで表示とクローズのコードを書いた所ですかね？
issueとファイルダウンロードして表示してみてそんな感じかなって掴んでます！
承認しておきます！ありがとうございます！

2022-04-01 00:45 UTC, hirotada-t commented
> daikichi.htmlの画面をindex.htmlの画面にモーダル表示するためにjsファイルを書き換えてるって感じですかね？ 今からモーダル表示する様にしていくって感じかな？？addEventListenerで表示とクローズのコードを書いた所ですかね？ issueとファイルダウンロードして表示してみてそんな感じかなって掴んでます！ 承認しておきます！ありがとうございます！

2022-04-01 00:47 UTC, merged