First updated daikichi.html
team-red-2203/workshop-omikuji pull request #6
Opened 2022-03-28 11:00 UTC by yoshiryo413

おみくじの結果画面の叩き台を作成しました！
確認お願いします！！

2022-03-28 12:26 UTC, satofumiya approved these changes
見やすくてめちゃいいです。

2022-03-28 12:28 UTC, hirotada-t requested changes
FBしたので、修正お願いします！

2022-03-28 12:28 UTC, hirotada-t commented on result/daikichi.html
> +
bootstrapが二回読み込まれているので、片方を削除ください。

2022-03-28 12:28 UTC, hirotada-t commented on result/daikichi.html
> +          <button type="button" class="btn btn-primary">
buttonタグを使う場合は、onclick属性でロケーションを移動させる記述の追記が必要ですね。

onclick="location.href='<url>'"
みたいな感じです。

2022-03-28 12:28 UTC, hirotada-t commented on style.css
> +
僕がスタイルまでいじっていたので、コンフリクトしちゃいますね。
コメントですし、マージする時に削除するのが良いかなと思います。

2022-03-28 15:23 UTC, yoshiryo413 commented on result/daikichi.html
> +
削除して済みです！
よっしゃ！！

2022-03-28 15:24 UTC, yoshiryo413 commented on result/daikichi.html
> +          <button type="button" class="btn btn-primary">
onclick属性把握！！実装します！！

2022-03-28 15:25 UTC, yoshiryo413 commented on style.css
> +
削除しました！これでコンフリクトなしでしょう！

2022-03-28 16:12 UTC, yoshiryo413 commented on result/daikichi.html
> -  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
最新のコミットで修正しました！！

2022-03-29 01:36 UTC, hirotada-t approved these changes
OKです！

2022-03-29 01:37 UTC, hirotada-t approved these changes

2022-03-29 01:50 UTC, hirotada-t requested changes

2022-03-29 01:50 UTC, hirotada-t commented on result/daikichi.html
> +          <button onclick="randomLink()" type="button" class="btn btn-primary">
onclickの中身が間違っています！
トップに戻るボタンなので、locationの行き先はindex.htmlにしないといけないです。

2022-03-29 01:56 UTC, hirotada-t approved these changes
こちらは大丈夫です！

2022-03-29 02:12 UTC, hirotada-t requested changes
onclickの修正をお願いします。

2022-03-29 10:02 UTC, yoshiryo413 commented on result/daikichi.html
> +          <button onclick="randomLink()" type="button" class="btn btn-primary">
ここ間違えてましたよね！朝気づきました！
今から修正入ります！

2022-03-29 10:23 UTC, yoshiryo413 reviewed
ボタンを押したらindex.htmlに戻る仕様に変更しました！！

2022-03-29 11:23 UTC, hirotada-t commented
ありがとうございます！

2022-03-29 11:24 UTC, hirotada-t approved these changes
ありがとうございます！

2022-03-29 11:24 UTC, merged